[package]
name = "rust-pprzlink"
version = "0.1.0"
authors = ["Michal Podhradsky <mpodhradsky@galois.com>"]
edition = "2018"
build = "build/main.rs"

[build-dependencies]
xml-rs = "0.2"
quote = "0.3"
rustfmt = "0.9"
changecase = "0.0.7"

[dependencies]
serde = "1.0"
serde_derive = "1.0"
